name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest
    

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Build
      run: xcodebuild -allowProvisioningUpdates -scheme "GoodNews" clean build CODE_SIGNING_REQUIRED=NO
