name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest
    

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Build
      run: xcodebuild clean build -project GoodNews.xcodeproj -sdk iphonesimulator -scheme "GoodNews" -destination "platform=IOS Simulator,OS=13.7,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
